package guiPackage;


import classPackage.User;
import classPackage.RestaurantSystem;
import guiPackage.administrator.MainPage;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Meng
 */
public class LoginGUI extends javax.swing.JFrame {

    /**
     * Creates new form LoginGui
     */
    public LoginGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("用户名");

        jLabel2.setText("密     码");

//        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("登     录      界       面");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton1.setText("登           录");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel3,javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel3)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(jButton1)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String name = jTextField1.getText(); 
        String password = jTextField2.getText();

     if(checkAdminStatus(name, password)){
        System.out.println("log in as administrator");
        MainPage adminPage = new MainPage();
        adminPage.setVisible(true);
        adminPage.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        dispose();
     }else if(checkCustomerStatus(name, password)){
        System.out.println("log in as customer");
        CustomerMainPageGUI adminPage = new CustomerMainPageGUI();
        adminPage.setVisible(true);
        adminPage.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        dispose();
     }
     else{
         JOptionPane.showMessageDialog(null, "Wrong Input.");
     }
     
     
       
    }//GEN-LAST:event_jButton1ActionPerformed

	private boolean checkAdminStatus(String name, String password){
       
        if(login(name, password,1)){
            System.out.print("success");
            return true;
            
        }else{
            System.out.print("not success");
        return false;
        }
    }
       private boolean checkCustomerStatus(String name, String password){
    	   System.out.println("name="+name+" psd="+password);
	       List<User> list = RestaurantSystem.getCustomerList();
	       if(login(name, password,0)){
	            System.out.print("success");
	            return true;
	            
	        }else{
	            System.out.print("not success");
	        return false;
	        }
        }
    
       private boolean login(String account, String password,int station) {
   		// 锟斤拷询SQL锟斤拷锟�   		
    	   String sqlWork = " select id,account,password,name,permission,remark "+
   						" from admintbl"+
   						" where account=? and password=? ";
   		String sqlGuest = " select id,account,password,name,permission,remark "+
   				" from guesttbl "+
   				" where account=? and password=? ";
   		// 锟斤拷菘锟斤拷锟斤拷庸锟斤拷锟斤拷锟�   		
   		DBUtil util = new DBUtil();
   		// 锟斤拷锟斤拷锟斤拷锟�   		
   		Connection conn = util.openConnection();
   		try {
   			// 锟斤拷锟皆わ拷锟斤拷锟斤拷锟斤拷
   			PreparedStatement pstmt;
   			if(station==1){
   				 pstmt = conn.prepareStatement(sqlWork);
   			}else  pstmt = conn.prepareStatement(sqlGuest);
   			
   			// 锟斤拷锟矫诧拷询锟斤拷锟斤拷
   			pstmt.setString(1, account);
   			pstmt.setString(2, password);
   			// 执锟叫诧拷询
   			ResultSet rs = pstmt.executeQuery();
   			// 锟叫讹拷锟矫伙拷锟角凤拷锟斤拷锟�   			
   			if (rs.next()) {
   				// 锟斤拷锟斤拷没锟斤拷锟较�   				
   				int id = rs.getInt(1);
   				String name = rs.getString(4);
   				int permission = rs.getInt(5);
   				String remark = rs.getString(6);
   				// 锟斤拷装锟矫伙拷锟斤拷息
//   				User u = new User();
//   				
//   				u.setId(id);
//   				u.setAccount(account);
//   				u.setPassword(password);
//   				u.setName(name);
//   				u.setPermission(permission);
//   				u.setRemark(remark);
   				
   				return true;
   			}
   		} catch (SQLException e) {
   			e.printStackTrace();
   		} finally {
   			util.closeConn(conn);
   		}
   		return false;
   	}
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
